# Numpy 기초연습문제

In [1]:
import numpy as np
# numpy 모듈을 불러온다

#### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.


In [2]:
a = np.zeros((3,4))
a

# 행의 개수가 3이고, 열의 개수가 4이며 0으로 이루어진 array를 출력한다

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

```
array([[ 1.,  2.,  3.,  4.],  
       [ 5.,  6.,  7.,  8.],  
       [ 9., 10., 11., 12.]])
```

In [3]:
for i in range(a.shape[0]):  # 배열a의 행의 수인 3이 range의 인수에 할당된다.
    for j in range(a.shape[1]): # 배열a의 열의 수인 4가 range의 인수에 할당된다.
        a[i, j] = i*4 + j + 1 # i와 j에 (0,0),(0,1), ~ ,(0,3),(1,0),(1,1), ~,
                               # (1,3), ~ ,(2,3) 까지 할당되면서 배열 a의 각 값을
                                # 할당한다.
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [4]:
num = 1

for i in range(a.shape[0]):       # 배열 a의 행의 수인 3이 range의 인수에 할당된다.
    for j in range(a.shape[1]):   # 배열 a의 열의 수인 4가 range의 인수에 할당된다.
        a[i, j] =  num             # a[0,0], a[0,1], ~ ,a[2,3] 까지 반복되면서
        num += 1                   # 배열 a의 값이 1,2,3,4,~,12 까지 할당된다.
a



array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

#### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [5]:
a[1,2]
# 배열 a의 2번째 행의 3번째 열의 값을 출력하는 것이다.

7.0

#### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [6]:
a.shape
# 배열 a가 몇행 몇열의 행렬인지를 표현해준다.

(3, 4)

In [7]:
a[[1], :]
# 배열의 두번째 행의 모든 값을 출력한다.

array([[5., 6., 7., 8.]])

#### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.
```
array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])
```       

In [8]:
a[:,[1, 2]]

# 배열 a의 2열과 3열의 모든 행이 출력되도록 한다

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

#### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.
```
array([1., 2., 3., 4., 5., 6.])
```

In [9]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

# array의 값을 배열a의 a[i,j]의 값으로 지정하는데, 이때 추출하는 a[i,j] 값은
# 배열 a의 모든 행과 열에 존재하는 데이터 중에서,
# if a[i,j] < 6 을 만족하는 조건에 대해서 출력하고
# 그 결과 형성된 array를 result에 할당하는 것이다.

array([1., 2., 3., 4., 5., 6.])

In [11]:
a[a <= 6] 
# 배열 a의 값중 6보다 작은 모든 값을 추출한다

array([1., 2., 3., 4., 5., 6.])

#### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.



In [12]:
b = np.random.random((3, 4))

# np.random패키지의 random 메소드를 이용해 3행 4열의 array를 
# 0~1 사이의 무작위 적인 값으로 만들 수 있다.

b

array([[0.82798696, 0.03677493, 0.55439282, 0.54699243],
       [0.66408492, 0.67782495, 0.11110748, 0.92369973],
       [0.22964672, 0.68445356, 0.04556411, 0.76568699]])

#### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [13]:
c = a * b 
# array간의 곲셈

c



array([[0.82798696, 0.07354986, 1.66317847, 2.18796971],
       [3.32042462, 4.06694968, 0.77775239, 7.38959786],
       [2.06682047, 6.84453563, 0.50120521, 9.18824391]])

#### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [15]:
d = b.T
# 행렬 b의 행과 열을 뒤바꾼 전치행렬은 T 메소드를 적용하여 생성할 수 있다.
d


array([[0.82798696, 0.66408492, 0.22964672],
       [0.03677493, 0.67782495, 0.68445356],
       [0.55439282, 0.11110748, 0.04556411],
       [0.54699243, 0.92369973, 0.76568699]])

#### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [17]:
print(a.shape, d.shape) 

# shape 메소드를 array에 적용하면 array의 차원을 출력할 수 있다.

(3, 4) (4, 3)


#### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [18]:
e = a.dot(d)
# 행렬 a와 행렬 d의 곱은 곱의 법칙을 따르며, dot 메소드를 통해서 가능하다.
e

array([[ 4.75268499,  6.0478562 ,  4.79799414],
       [12.61727354, 15.55472455, 11.69939968],
       [20.48186209, 25.0615929 , 18.60080522]])

#### 12. e에 대하여 각 열의 합을 계산하시오.

In [19]:
np.sum(e, axis=0)

# axis파라미터를 0으로 설정하면, 행렬 e를 수직방향으로 더한 값을 출력할 수 있고,
# 1으로 설정하면, 수평방향으로 더한 값을 출력할 수 있다.
# 이 경우는 수직 방향으로 더해야 하므로, 0으로 설정해야 한다.

array([37.85182061, 46.66417365, 35.09819904])